include(${CMAKE_SOURCE_DIR}/third-party/cxxopts.cmake)

add_executable(batch-solver batch-solver.cpp)
target_link_libraries(batch-solver pdexa::ext cxxopts::cxxopts)
target_compile_features(batch-solver PRIVATE cxx_std_17 hip_std_17 cuda_std_17)
if (GINKGO_BUILD_CUDA)
    enable_language(CUDA)
    set_source_files_properties(batch-solver.cpp PROPERTIES LANGUAGE CUDA)
    target_compile_definitions(batch-solver PRIVATE GKO_COMPILING_CUDA=1 GKO_DEVICE_NAMESPACE=cuda)
    target_compile_options(batch-solver PRIVATE --expt-relaxed-constexpr)
elseif (GINKGO_BUILD_HIP)
    enable_language(HIP)
    find_package(hip REQUIRED)
    target_link_libraries(batch-solver hip::host)
    set_source_files_properties(batch-solver.cpp PROPERTIES LANGUAGE HIP)
    target_compile_definitions(batch-solver PRIVATE GKO_COMPILING_HIP=1 GKO_DEVICE_NAMESPACE=hip)
endif ()
